### ISSUE TITLE
Add default commands

### ISSUE THREAD

**Issue by trevorhauter** [trevorhauter/gitportal.nvim#40]
Add some default user commands like. Based on some feedback...
> one thing is missing is default user commands like GitPortal open would open file from link and GitPortal create or just gitportal would create the link

So let's add a few more quality of life commands directly available for users. Creating the link, copying it to clipboard, opening links, etc!

**Comment by tronikelis** [comment]
hey can i take this?

**Comment by trevorhauter** [comment]
@tronikelis Absolutely
