### ISSUE TITLE
Gives a message "not found"

### ISSUE THREAD

**Issue by lispercat** [trevorhauter/gitportal.nvim#46]
After the basic installation when I say "require("gitportal").open_file_in_browser()" it just shows a quick message "not found" and nothing happens. 
I am in wsl ubuntu environment, btw. Could it be that there a browser can't be found?
Are there logs that I can see?

**Comment by trevorhauter** [comment]
@lispercat Sorry you're having trouble! There are not any persistent logs, that's something I need to add. I think this is likely a result of lua not knowing how to find your browser, or how to launch it with the right command.

Can you run the following command inside neovim, via command line mode and let me know if you get the same "not found" error?
`:lua os.execute("xdg-open 'https://www.google.com'")`

It's possible I'm inaccurately determining when to use what command. Could you run this command inside neovim via the command line mode and let me know if this works for you?
`:lua os.execute("open 'https://www.google.com'")`

and lastly, could you let me know the output of this command (in neovim via command line mode) so I can ensure your use case is supported?
`:lua print(vim.loop.os_uname().sysname)`

Sorry for the inconvenience. I'll work on adding logs this weekend

**Comment by trevorhauter** [comment]
@lispercat Perfect, that's super helpful. I'm going to do some digging this evening (I'm on east coast time in US) and see if I can detect this case and use the appropriate command, but I'm also going to add a setting that lets you specify the command required to open links in browsers as well, I'm sure you're not the only one.

I'll ping you when it's ready! Thanks so much :-)

**Comment by trevorhauter** [comment]
@lispercat I've added the ability to specify the browser opening command in the config. Instructions are on the readme!

I would still like to make this plugin smarter about which command to use, so I'm leaving this issue open for now as I learn more about how to do that. But in the meantime this should make the plugin usable! :-) Let me know if you have anymore troubles

**Comment by trevorhauter** [comment]
@lispercat Alright, I think I may know how to make this detect ubuntu from wsl. Can you do me a favor and provide me the output from the following cli command? 
- `uname -a`

Alternatively, if you don't wish to provide the whole output, could you just let me know if there is an identifying string in the output? Perhaps something like `Microsoft` or `wsl`, or something that gitportal can use to determine if it needs to use an alternate command?

**Comment by lispercat** [comment]
Linux CAL-2880 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55
UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by trevorhauter** [comment]
@lispercat thank you! I should hopefully have some time tonight to push a fix for this.

**Comment by trevorhauter** [comment]
@lispercat Hey! GitPortal should work automatically now for your linux version without any issue, and with no need to specify the browser command. If this issue still persists, please re-open this issue! I really appreciate your feedback and patience with this issue and hope you enjoy using the plugin :-)

**Comment by lispercat** [comment]
Thanks, Trevor
