### ISSUE TITLE
Feature Request: Add suport for GITLAB

### ISSUE THREAD

**Issue by KamilKleina** [trevorhauter/gitportal.nvim#51]
Feature Request: Please add support for GitLab, including custom self-hosted GitLab instances. This would greatly enhance compatibility for users relying on self-hosted setups.

**Comment by trevorhauter** [comment]
Thanks for taking the time to request the feature! I'm starting on Gitlab now. I'm doing my best to add this in a modular way so hopefully once I wrap my head around how the different hosts differ, and how self hosting works, it should be quick to add the remaining hosts!

**Comment by KamilKleina** [comment]
Awesome dude, I really look forward to start using your plugin

**Comment by trevorhauter** [comment]
@KamilKleina Hey, this should be working for gitlab now! I'm leaving this issue open as I have not added any support for self hosting yet. Please let me know if you run into any troubles with this!

**Comment by tomi2108** [comment]
Hey, thanks a lot for gitlab support, opening in browser works perfectly for self hosted instances, opening in neovim not so much, at least not for me. Here is the error I get: 
`gitportal.nvim/lua/gitportal/lua_utils.lua:7: bad argument #1 to 'gmatch' (string expected, got nil)`

Here is an example URL: https://gitlab-ee.agil.movistar.com.ar/mimovistarempresas/frontend/app-shell/-/blob/feature/mfError/src/hooks/useSessionTimer.js?ref_type=heads

Thanks for the plugin, it has been really hepful.

**Comment by trevorhauter** [comment]
@tomi2108 Is this the correct structure of the url?
``` lua
-- https://gitlab-ee.agil.movistar.com.ar/mimovistarempresas/frontend/app-shell/-/blob/feature/mfError/src/hooks/useSessionTimer.js?ref_type=heads```

- `mimovistarempresas` - gitlab org
- `frontend/app-shell` - repo
- `feature/mfError` - branch 
- `src/hooks/useSessionTimer.js?ref_type=heads` - file path

**Comment by tomi2108** [comment]
@trevorhauter mimovistarempresas is the name of the group (kind of like github's orgs), and frontend is a subgroup, app-shell is the actual name of the repo. Subgroups can be nested infinitely, and names are case insensitive, the 'actual' name of the group is miMovistarEmpresas

**Comment by trevorhauter** [comment]
@tomi2108 This should be working now. Whenever you're back working on your repo, can you give it a shot and let me know?

**Comment by tomi2108** [comment]
Getting this error now 

`Git host link > https://gitlab-ee.agil.movistar.com.ar/mimovistarempresas/frontend/app-shell/-/bl
ob/feature/mfError/src/pages/facturas/quiero-pagar/index.jsx?ref_type=heads#L3
Could not successfully parse githost url!`

**Comment by trevorhauter** [comment]
@tomi2108 Oh darn... 
Is this the correct meta data for the link?
```
branch = feature/mfError
file_path = src/pages/facturas/quiero-pagar/index.jsx
``` 
And, if you run `git show-ref --heads $branch_name` do you get an output via your command line?

**Comment by tomi2108** [comment]
@trevorhauter Yes, the meta data is correct. After switching manually once to the branch it its working as expected. Even if another branch is checked out, the plugin switches branches correctly. Maybe the branch needs to exist locally? 
Thanks for the work :) awesome plugin.

**Comment by trevorhauter** [comment]
@tomi2108 Oh yes that's it! The branch must be available locally. I should really make that more clear, and add a better error message.

Woohoo! That is so exciting! Thanks so much for using the plugin, and for helping me get self hosting support for gitlab. Your troubleshooting with me is so helpful. Let me know if you have any other issues!!

**Comment by trevorhauter** [comment]
Alright y'all I'm closing this issue, gitlab is up and running! If you run into any problems at all please open an issue!

**Comment by KamilKleina** [comment]
@trevorhauter I am not sure if I should comment here with the issue or somewhere else:

self-hosted gitlab instance doesn't work correctly
I am in the repo and I am trying to open a file:
path: $REPO/configurations/lib/data_lake/glue.py
and I am getting an error: couldn't determine git host
where host is: https://dev.$COMPANY_NAME.com

and running:
```
git config --get remote.origin.url 
 git@ssh.dev.$COMPANY_NAME.com:random_word/random_word_2/$REPO.git
````

**Comment by tomi2108** [comment]
> @trevorhauter I am not sure if I should comment here with the issue or somewhere else:
> 
> 
> 
> self-hosted gitlab instance doesn't work correctly
> 
> I am in the repo and I am trying to open a file:
> 
> path: $REPO/configurations/lib/data_lake/glue.py
> 
> and I am getting an error: couldn't determine git host
> 
> where host is: https://dev.$COMPANY_NAME.com
> 
> 
> 
> and running:
> 
> ```
> 
> git config --get remote.origin.url 
> 
>  git@ssh.dev.$COMPANY_NAME.com:random_word/random_word_2/$REPO.git
> 
> ````
> 
> 

I would open a new issue just in case :)
